compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  react-map-gl@*:
    dependencies:
      react-dom: "*"
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
