packageExtensions:
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  react-map-gl@*:
    dependencies:
      react-dom: "*"
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
